version: '3.9'

services:
  backend:
    image: fastapi-learning:v1.3
    container_name: "fastapi-learning"
    env_file:
      - .env
    command: uvicorn blog.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    networks:
      - default

  # backend:
  #   build:
  #     context: .
  #   ports:
  #     - "8000:8000"  # Maps host port 8000 to container port 8000
  #   environment:
  #     - SECRET_KEY=${SECRET_KEY}  # Passes SECRET_KEY from .env
  #   volumes:
  #     - .:/app  # Mounts your local code into the container for development
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
