"""Add created_at column to blogs

Revision ID: 83d31938cae3
Revises: c91e9fc57aa0
Create Date: 2024-11-23 02:05:02.529066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d31938cae3'
down_revision: Union[str, None] = 'c91e9fc57aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'updated_at')
    # ### end Alembic commands ###
